spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    druid:
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.git,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          slow-sql-millis: 1000    #          慢查询时间
          enabled: true

        wall:
          enabled: true
#          config:
#            update-allow: true


mybatis-plus:   # 下面两个路劲文件必填，classpath指的是内路径
  config-location: classpath:mybatis/mybatis-config.xml  # 指定mybatis的配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  # 指定mybatis的mapper映射文件位置
